---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snapshot-controller
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.0.4
    digest: sha256:e6dd88b088086c9c9f0cd6b0b5f2cd6a0d78209f5959157842e865386649ee34
  url: oci://ghcr.io/piraeusdatastore/helm-charts/snapshot-controller
