---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  config:
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"
    auth:
      oauth_auto_login: "true"
      oauth_allow_insecure_email_lookup: "true"
    auth.anonymous:
      enabled: "false"
    auth.basic:
      enabled: "false"
    auth.generic_oauth:
      enabled: "true"
      name: Authelia
      icon: signin
      scopes: openid profile email groups
      empty_scopes: "false"
      login_attribute_path: preferred_username
      groups_attribute_path: groups
      name_attribute_path: name
      role_attribute_path: contains(groups[*], 'admins') && 'Admin' || 'Viewer'
      use_pkce: "true"
      auth_url: "https://auth.${SECRET_DOMAIN}/api/oidc/authorization"
      token_url: "https://auth.${SECRET_DOMAIN}/api/oidc/token"
      api_url: "https://auth.${SECRET_DOMAIN}/api/oidc/userinfo"
      client_id: grafana
    date_formats:
      use_browser_locale: "true"
    log:
      mode: console
    metrics:
      enabled: "true"
    news:
      news_feed_enabled: "false"
    plugins:
      plugin_admin_enabled: "false"
    security:
      angular_support_enabled: "true"
    server:
      enable_gzip: "true"
      root_url: "https://grafana.${SECRET_DOMAIN}"
    database:
      type: $__env{GF_DATABASE_TYPE}
      host: $__env{GF_DATABASE_HOST}
      name: $__env{GF_DATABASE_NAME}
      user: $__env{GF_DATABASE_USER}
      password: $__env{GF_DATABASE_PASSWORD}
      ssl_mode: $__env{GF_DATABASE_SSL_MODE}
  deployment:
    spec:
      strategy:
        type: Recreate
      replicas: 1
      template:
        spec:
          initContainers:
            - name: init-db
              image: ghcr.io/home-operations/postgres-init:18
              envFrom:
                - secretRef:
                    name: grafana-secret
          containers:
            - name: grafana
              envFrom:
                - secretRef:
                    name: grafana-secret
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: {drop: ["ALL"]}
          securityContext:
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
  httpRoute:
    spec:
      hostnames:
        - "grafana.${SECRET_DOMAIN}"
      parentRefs:
        - name: envoy-internal
          namespace: network
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: ceph-block
  disableDefaultSecurityContext: All
