---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: intel-device-plugin-gpu
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/intel/helm-charts/intel-device-plugins-gpu
  ref:
    tag: 0.36.0@sha256:6f09a445227e1bec9d625f0c384182480ce7fc3c63c634549c8f813f1a77a3d0
