---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: intel-device-plugin-gpu
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/intel/helm-charts/intel-device-plugins-gpu
  ref:
    tag: 0.37.1
    digest: sha256:35195c40cbae8991d82ed16c0df85414f387a777240e220d61b3f294b6b1eed6
