---
apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
data:
  garage.toml: |
    metadata_dir = "/data/garage/meta"
    data_dir = "/data/garage/data"
    db_engine = "lmdb"

    replication_factor = 1

    rpc_bind_addr = "[::]:3901"

    [s3_api]
    s3_region = "us-east-1"
    api_bind_addr = "[::]:3900"

    [admin]
    api_bind_addr = "127.0.0.1:3903"
