---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: garage-secret
    template:
      engineVersion: v2
      data:
        GARAGE_RPC_SECRET: "{{ .GARAGE_RPC_SECRET }}"
        GARAGE_METRICS_TOKEN: "{{ .GARAGE_METRICS_TOKEN }}"
        GARAGE_S3_ACCESS_KEY_ID: "{{ .GARAGE_S3_ACCESS_KEY_ID }}"
        GARAGE_S3_SECRET_ACCESS_KEY: "{{ .GARAGE_S3_SECRET_ACCESS_KEY }}"
        API_ADMIN_KEY: "{{ .GARAGE_ADMIN_TOKEN }}"
        AUTH_USER_PASS: "{{ .GARAGE_WEBUI_AUTH }}"
  dataFrom:
    - extract:
        key: garage
