---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: garage-secret
    template:
      engineVersion: v2
      data:
        GARAGE_RPC_SECRET: "{{ .rpcSecret }}"
        GARAGE_ACCESS_KEY_ID: "{{ .accessKeyId }}"
        GARAGE_SECRET_ACCESS_KEY: "{{ .secretAccessKey }}"
  data:
    - secretKey: rpcSecret
      remoteRef:
        key: garage-rpc-secret
    - secretKey: accessKeyId
      remoteRef:
        key: garage-access-key-id
    - secretKey: secretAccessKey
      remoteRef:
        key: garage-secret-access-key
