---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
  - ./scrapeconfig.yaml
configMapGenerator:
  - name: kube-state-metrics-config
    files:
      - kube-state-metrics.yaml=./resources/kube-state-metrics.yaml
generatorOptions:
  disableNameSuffixHash: true
