---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 87.17.0
    digest: sha256:b8be855d3f25e045c878f917170168d1f4e7262277dcf4fc8d64bc630abd9b16
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
