---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 87.10.1
    digest: sha256:ed3163fc6ec723830c21ae328a6f3dd3861afeedd712bf72a556c891990057a6
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
