---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name node-exporter
spec:
  staticConfigs:
    - targets: ["192.168.20.1:9100"]
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
