apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:6/TTVQ==,iv:nkHwJylEHmm2Z2ekf5TYIfChEh318H1sWtbzZBBXKUY=,tag:RmI+dZhVJxGD5jbSfI1G9w==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:1X0ESN3sv9gXOKXkqR5AtAJBS+UDDolyMCsKvKkt+aqsxOMW/LULETrHNiA=,iv:qv+0znY9aW2sr9ld4OPzy2m6SmBShya4L67YUvDHAHA=,tag:coguj/VMvlau0RRfiXDMKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZzU0Q3VIZERoL1NPVDgw
            MTJ5UjBHTUU2eVVPR2xaWmpxVXAvcFo2WFRjClRDZCt0QmExRkdaM09NbFhvZXJC
            eC8xdHlZRHVkT3ZjVGNnaFRJUlF6S0EKLS0tIDg4SEU5YmhXWWFuSy9oVmIrVkIr
            OWdUZkwrT3FESFhUQWhqQW5GMTgxR00Kb8/uVcLKChbGO/Q95fadehhBpbis/Dzx
            1B/mxZahcqhUE6+oHFv0dGi1y71V3pMh/2BvqBkO64wUlBar51Zbfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-26T05:45:37Z"
    mac: ENC[AES256_GCM,data:k5UXch/riq45eO42Tgw6+rlRJdN7BZ3WGWXRNWVAgbIYpCjlcQUAKAAx/Up3pqDNlNZx4fEdef6aY+XN/d5QiODaLTGn/Ft5yh1bcmaXnxAsw/5AvQODPstANtjv+wL9MksyJwjRQQS1IzWvSFjOCgvP8SZ5Xu9tqkC/btER684=,iv:qe+WRxw86g0nMQgTOoughk5zWjaZAbV1KBSqp3ZhWKQ=,tag:htFj4bXUNda69qDW3+Q2eg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
