apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-b2-secret
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:p00d7Cqk4J4YyVtJISLiv3V5Ok3To0OSPdyatr7LDtcUD/BsQPkQgHKX,iv:FasWCEXPTPCW6EQugVyfgWC0DYM930P6ioZvXjUbBn4=,tag:Hf4KoNbTlXv3M9BrP5ghxA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Cu35d+AJrsvgu77eNVJDR8IgmIEzr0TysYJQHixu96xxUe1VYcGS77B3cR2lBXYPPuhmFcl1f3ozToRz43hU8g==,iv:+axqe9yblwLwlUfEXvk6sgHAdkKIGZpfe5uLH4xwfvY=,tag:LjZ7FRbH8IjnrOLAeDBbYQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:9V6/TwG5LYXjg2gBynKPpcHt7diS/Zuiaw==,iv:6VD6Fu5/mTSDTjgEVNp0Z0cXRQBWGQIOSAZg42zXbsY=,tag:5DhJZnOsRwQ3fPlKuOYkqQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:n7z/62a4PHH86BqjSwmR+liinA2vfjfaEcRt9faFPg==,iv:Xm+9otz7fOS6T+PtGt76z3fntIuvlsnnc7jitBqL3wM=,tag:9YiMujh7BR930dGTRixIPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZzU0Q3VIZERoL1NPVDgw
            MTJ5UjBHTUU2eVVPR2xaWmpxVXAvcFo2WFRjClRDZCt0QmExRkdaM09NbFhvZXJC
            eC8xdHlZRHVkT3ZjVGNnaFRJUlF6S0EKLS0tIDg4SEU5YmhXWWFuSy9oVmIrVkIr
            OWdUZkwrT3FESFhUQWhqQW5GMTgxR00Kb8/uVcLKChbGO/Q95fadehhBpbis/Dzx
            1B/mxZahcqhUE6+oHFv0dGi1y71V3pMh/2BvqBkO64wUlBar51Zbfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-26T05:01:31Z"
    mac: ENC[AES256_GCM,data:QoasWATBvbKGcqV1Er/3U0oD3U69FHMyFAI+JKqepweR7w8R88R5LE3kUfbXGIBcU0ZA6sJfVvOA0mO4DMEa16wM8wv1PBFsVDdpjohqdCBf4WfHHif1/unm34dDHhjNmT4y3Ch7ByVIAmjDiPIYP4aQt53DZtxu88BCTHpvo8s=,iv:q9eObIJGI8SwanQI1xgLmuQPzesJunICBx5QceNLJw8=,tag:aoD46bAD+MNTXyni/bWIyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
