---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs-collector
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.3.4
    digest: sha256:4c2fdfd92da574db15457a1bbf1bcef28e95140cb89593f7a76d4ae1ec59b396
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-collector
