---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs-collector
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.3.3@sha256:714a6bc41ad4493814110230f60734a85d0171200560cf25f0e62d4581f616cf
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-collector
