apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:b9ybAZg81FW+gQPfVh4JpxM481XqU+QvHDlXHX+tXwn8svhL,iv:WPIj01Y2xU6snQ1DvOM5DwLOtetkys2h70vyKImayP0=,tag:+X7+Gl0N07UYtVoiGD1iuQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:DlgzZKibMzVqftB/xwJfIZGH9pVlSlFUclQD2XbFuplzY4wIXOQhsma6Pt9N4Lft73lOrU5TD2lHtquHePt1/LzE4utab7iGQ6sNJ0b6ImGKwEaVlhOidnFuyYLoD1p0k8iHJLxp5TJlH2MoXxJBcW1XiYBKZOB4V1+16UsnhBkcSlWZe1FnzyRXabK31KCgzcexBG8eYgJ1qYQJcD5OWjZul9IVKFheeJejDJW6nQ==,iv:NF67pAsEOic7Hu6ceBUwtbqvf1InsLa0QDl9OcsErcU=,tag:BbPuEVSo5W3svhjKSi2TLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbHU3ZHZ2Y25Fb0xFN3NY
            dGFWMDZIbWEwbkVmUEJOd0RUNXNrOFBzU0hRCmFZMHRsUzRsVVBvRUdVNU5qSStj
            cC9YMVpiVWg1YlVWeWZWdHZTelMxbkEKLS0tIFc4KzBYMVZiWHltN2hjTC84UFcx
            U2Nsdk9pMlZqVGYrMHVWVm40aGlneDAK1lcjZ0E2ocII2UHRvk2spJISHolLdjOT
            1PWQA/N9U85x5IbNGHahPwwpXB/sNE1sutR64Z6NrggTDisWij2+lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-19T02:09:26Z"
    mac: ENC[AES256_GCM,data:ocXhFXXjiaRTcCLCtaELFWxByM4fRHHHo1oGFREqg0di+3nizfxBbR/Gd9TR0/zx/6YNQRsxlvei+pDxTdXAtqD44b03ER2z3cVGc1s1A9/Cpkg8dmSXYajbSi3dnToadl/b9qMOHx+2+r3ZtuPxfEB7uN3Yn7yilXkj576nHqg=,iv:nl6aF0N3qDSosCQD0FGu82rIUEXeLD4li6D68ORJhc8=,tag:z5goUgCv7Zhiw1xyvnZnuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
