apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:b6v84BP+nMrvYbMZHrNz2ZyAEWnObypoUAe/HhvvLIHSSMafkYn7oQ==,iv:Xt9jLqmzbSxOPy0o0CgnxcElHU4tXb1Uz1SpgM8hBy8=,tag:Lyf/8KlKkshPPRGalJzxDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2S095LzI0Vi9La0NqWEhX
            SlhtYTR5Zyt4aHRGNGd6VmNSY0V1cVhoMWpnCkNCb3VTYVNsMTl4ZkIzY3JuclBa
            MjFQeksrMmNpbklGUkVLc0VwZ3c5bkUKLS0tIDJSeDNCUUNjQlV1aXc2MnlXdzI2
            ZWdsbmU2dktHYWViZW5xN1V4VCtxb3cKQfgxV+8TEeOodBbRMMFIlegW49bnVStN
            4+LBDY0n+Q2TmSjMDMPc9XY74TchnRjbI0N55kY7/C6bAmnuuXTOEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T23:31:38Z"
    mac: ENC[AES256_GCM,data:Ri8vM5HD09PVLQ0TV+AFdpxl16D37rZaqWjrKIZKAlfstbfvrMk61ZPKUzfGdF0lc6BEuCjxFg2p1rRjGwR934WiPqpahZK/ecXf3sQ//u5h6uNUqXeOkRAqGYUf05HCUs3XtceocY548N7cZrDw1R9Mu++KRNlehHa7WnfymLI=,iv:VppzwZiJVyqVWECga+UoISpejvpU4zupuK8CwS6jkZI=,tag:9ILdxjv2fNACKw3yM9aCgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
