apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:nC15Ng/y7iUkYLCWeACZoesNsJW7cZNSCui7uff7StkTQtygj0L3fMin4hK8I3zHcPSUJzo=,iv:20k5bhv8ExEuAx5sEMGI7Mcz7T/V0J5CdhFQ/dRVGoA=,tag:ZIfxw/vOfgkpCRpF9yXTKA==,type:str]
sops:
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2S095LzI0Vi9La0NqWEhX
            SlhtYTR5Zyt4aHRGNGd6VmNSY0V1cVhoMWpnCkNCb3VTYVNsMTl4ZkIzY3JuclBa
            MjFQeksrMmNpbklGUkVLc0VwZ3c5bkUKLS0tIDJSeDNCUUNjQlV1aXc2MnlXdzI2
            ZWdsbmU2dktHYWViZW5xN1V4VCtxb3cKQfgxV+8TEeOodBbRMMFIlegW49bnVStN
            4+LBDY0n+Q2TmSjMDMPc9XY74TchnRjbI0N55kY7/C6bAmnuuXTOEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T05:49:02Z"
    mac: ENC[AES256_GCM,data:X22lL4M2xVgxWuVlt/WFGbbBQAz28XYPYBiqVU8wSojG892Ji7ULPt6DuTm61R2jzM7/PG3mO9y4CpfAwGKJW1g4RZ7p/XDHZwpwOQKNuAhy8DutQsjBUoSmruyTqHtAAJ4tl/IAfAjBgaISCfWCSjySToF3qqzKNqLz5FG17N4=,iv:xX0AHUrubC3mqa7EkwlX7S8lcORqOWZfHjJtAjzT2Do=,tag:Xqfg4bVgXUCSzprRMB84Nw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
