apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hQYalxgr48+row==,iv:V/RklmvtxRIF5I64swi99k7SzMQ+Sbo9dysgo3qB6VU=,tag:BF92qyrq0ba6RaXXAvZCMQ==,type:str]
    SECRET_BITWARDEN_ORGANIZATION: ENC[AES256_GCM,data:VTfnLcvCEEb6OvzcASaobOS4z6X5RqGer+3whVmT+xOwpqB2,iv:zbFsWxEEzWo3fyKfrI/4YwzZYiROzH4qTLUVeHbi8Vg=,tag:LaniINfgayKNnNEd7w6ChA==,type:str]
    SECRET_BITWARDEN_PROJECT: ENC[AES256_GCM,data:8YG7ssHmIkf/+kwRUFPlUPYNaiQvR1PpZHUnMk7XYHwimyhX,iv:Yvh9P0McTKE2BSwrYu6DXwMzfc3ma7B60MVCb9QdmW4=,tag:oXChhR/QIVqEcYjFPGr6iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZDFGVEJWUlNZdmV4enl0
            N1grSmloVkhaaXA3MVMrbHZqSzZIMmVwOW40ClJoTTAwcm13MXdSdVNjNCtFSlg0
            eHhlZkE0S3dUYzl3UVgzbHcwalltMFEKLS0tICt3dzZQOWh6STBSS0IxRlp1NFRQ
            Rm00NklRNFR4TExheVJzdjRmazVLTjgKY2lJFluLkVi59wjsFITSNQ7Zpct4A6fE
            5arxMXdPoozIbsfnrLv28kVTAMezWhrWdZjdZhkCTMLmvFNgjfnW4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T22:53:18Z"
    mac: ENC[AES256_GCM,data:fdWsQ0axVnN2t2G/GMSkEcDG8LFw1WhSmFp7QxyRCfQ72Xa0TaDK1XhAnyB5WZjgMXfcmg+uAJ7jNZ/I+a7r0WOwqExDXVDjcsuD74R+dPrVODSP9gpoalnsXD9GM6slGqLZ4WLpGoJ7rI2lInsB2+6WGfw063TszxcQ7HxVLrQ=,iv:K6pU5MZ0Pvh45aiQFuJpYQn2oJ8RBP8hCsvxofcaN0w=,tag:9h0uRCkXIl0TSoU0UQQpqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
