apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hQYalxgr48+row==,iv:V/RklmvtxRIF5I64swi99k7SzMQ+Sbo9dysgo3qB6VU=,tag:BF92qyrq0ba6RaXXAvZCMQ==,type:str]
    SECRET_BITWARDEN_ORGANIZATION: ENC[AES256_GCM,data:VTfnLcvCEEb6OvzcASaobOS4z6X5RqGer+3whVmT+xOwpqB2,iv:zbFsWxEEzWo3fyKfrI/4YwzZYiROzH4qTLUVeHbi8Vg=,tag:LaniINfgayKNnNEd7w6ChA==,type:str]
    SECRET_BITWARDEN_PROJECT: ENC[AES256_GCM,data:8YG7ssHmIkf/+kwRUFPlUPYNaiQvR1PpZHUnMk7XYHwimyhX,iv:Yvh9P0McTKE2BSwrYu6DXwMzfc3ma7B60MVCb9QdmW4=,tag:oXChhR/QIVqEcYjFPGr6iw==,type:str]
sops:
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZDFGVEJWUlNZdmV4enl0
            N1grSmloVkhaaXA3MVMrbHZqSzZIMmVwOW40ClJoTTAwcm13MXdSdVNjNCtFSlg0
            eHhlZkE0S3dUYzl3UVgzbHcwalltMFEKLS0tICt3dzZQOWh6STBSS0IxRlp1NFRQ
            Rm00NklRNFR4TExheVJzdjRmazVLTjgKY2lJFluLkVi59wjsFITSNQ7Zpct4A6fE
            5arxMXdPoozIbsfnrLv28kVTAMezWhrWdZjdZhkCTMLmvFNgjfnW4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T06:25:07Z"
    mac: ENC[AES256_GCM,data:VBi7pnz98UpW0KH3Q0Y8MfAJShrADykDHx4uHK4G3KdzzONgQNj+89P1KVM2zRlEmn6D3Ahkilz2Ae8+zGgMgR1y9qhRdZPaWjYoFIzKmKvceG/yAuZa1NE5koXqWgZy8ztfu48MvbG5V16O0x7ByPxIESXS304fCVbRPAAs24k=,iv:ldtE1EMe3EqKaYUHk0X6dOrKTtkFlPSJCYagy3mo6TU=,tag:jl/pRSBYnogUUlO/dUScXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
