---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-instance
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.54.0
    digest: sha256:b2b09726593f1e0efb4a943ce3743c74db4da4585c139f5431655b25ee14354c
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-instance
