apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:EBghBqs7C/LjORiyPDRwzTkoTx1jLp6NbE/Pl+AfapU=,iv:DDwL/KrHO6ZFbkIYRUbVLK8HQlZC3WphctC6aG1qW4k=,tag:X6VHIRA6VbcfoCWtbLxipA==,type:str]
sops:
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2S095LzI0Vi9La0NqWEhX
            SlhtYTR5Zyt4aHRGNGd6VmNSY0V1cVhoMWpnCkNCb3VTYVNsMTl4ZkIzY3JuclBa
            MjFQeksrMmNpbklGUkVLc0VwZ3c5bkUKLS0tIDJSeDNCUUNjQlV1aXc2MnlXdzI2
            ZWdsbmU2dktHYWViZW5xN1V4VCtxb3cKQfgxV+8TEeOodBbRMMFIlegW49bnVStN
            4+LBDY0n+Q2TmSjMDMPc9XY74TchnRjbI0N55kY7/C6bAmnuuXTOEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T06:01:35Z"
    mac: ENC[AES256_GCM,data:hwgeqQkMymqYgfRh0XaBve7TVxK7i5tctkuvYIIBKjtCNU+cZc8VEkuv5cOhuMnwHMa2+bfrgg9Z9htulG8YeDVWu/+Z0oD1E1OI4sBe43giG/bEL+IyBJOlYbDDCD4Oblr2QGexLWnrim7O/auIUpKkOtEJRbb1T+vmkbOW13M=,iv:YF3XpNxGi6k0sG1KZdHX19sLgS0Wsl08F1vI57ZU7Oc=,tag:MUxg/oIGfqphyzmABd/wgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
