---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: qbittorrent-secret
    template:
      engineVersion: v2
      data:
        PUSHOVER_TOKEN: "{{ .QBITTORRENT_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
  dataFrom:
    - extract:
        key: pushover
    - extract:
        key: qbittorrent
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gluetun
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: gluetun-secret
    template:
      engineVersion: v2
      data:
        VPN_SERVICE_PROVIDER: "{{ .GLUETUN_SERVICE_PROVIDER }}"
        WIREGUARD_PRIVATE_KEY: "{{ .GLUETUN_WIREGUARD_PRIVATE_KEY }}"
        WIREGUARD_ADDRESSES: "{{ .GLUETUN_WIREGUARD_ADDRESSES }}"
        SERVER_CITIES: "{{ .GLUETUN_SERVER_CITIES }}"
  dataFrom:
    - extract:
        key: gluetun
