---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: qbittorrent-secret
    template:
      engineVersion: v2
      data:
        PUSHOVER_TOKEN: "{{ .QBITTORRENT_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
  dataFrom:
    - extract:
        key: pushover
    - extract:
        key: qbittorrent
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v
kind: ExternalSecret
metadata:
  name: gluetun
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: gluetun-secret
    template:
      engineVersion: v2
      data:
        WIREGUARD_PUBLIC_KEY: "{{ .GLUETUN_WIREGUARD_PUBLIC_KEY }}"
        WIREGUARD_PRIVATE_KEY: "{{ .GLUETUN_WIREGUARD_PRIVATE_KEY }}"
        WIREGUARD_ENDPOINT_IP: "{{ .GLUETUN_WIREGUARD_ENDPOINT_IP }}"
        WIREGUARD_ENDPOINT_PORT: "{{ .GLUETUN_WIREGUARD_ENDPOINT_PORT }}"
        WIREGUARD_ADDRESSES: "{{ .GLUETUN_WIREGUARD_ADDRESSES }}"
  dataFrom:
    - extract:
        key: protonvpn
