apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:2qRQy9619R28GGt09MemjxIDB2jf0pXjcl7f3BoNdogPF04wPY9AIPtTkNwS3n0x2hczuRfr5V464cNm4uuw0Q==,iv:g36OFrJnTAXeJVYXqLaERQgbE97AhD6h0ATS8WNSTvU=,tag:OBiiamL6n4yvur7g0bE+8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZzU0Q3VIZERoL1NPVDgw
            MTJ5UjBHTUU2eVVPR2xaWmpxVXAvcFo2WFRjClRDZCt0QmExRkdaM09NbFhvZXJC
            eC8xdHlZRHVkT3ZjVGNnaFRJUlF6S0EKLS0tIDg4SEU5YmhXWWFuSy9oVmIrVkIr
            OWdUZkwrT3FESFhUQWhqQW5GMTgxR00Kb8/uVcLKChbGO/Q95fadehhBpbis/Dzx
            1B/mxZahcqhUE6+oHFv0dGi1y71V3pMh/2BvqBkO64wUlBar51Zbfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-27T04:08:43Z"
    mac: ENC[AES256_GCM,data:JyEar3Mtf4DuZxx2VXHYJC+LaRn09CBvOzo5SK8v2cNTCH+EZdSH0W7QArJxqK09h+LKrRCGxDqC7UkcI2e0ZDYGyWsQ18yxvEhA+T4scr/6iIwIp2a7thi8j4210YOobPVR/q8H3y+S4KtWco2zWiGkseoPB0yVnGT53a89v0I=,iv:fxWiGsbrrbScIWdqKfvxKND1v7SF4fJfTYWSN8F0gM4=,tag:/5zQq36Isat5LnfV9mqECA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: kopia-repository-secret
stringData:
    repository.config: ENC[AES256_GCM,data:DiyQv6XePsAqyqcvTmLY6NLiRuWwU7bbt7b3AeXg7MpCfa9mbb1CCKlLcjfaq8HcuJ+63kYlBtGU6tF3OJU05AdJJDxHF3dKG5eyqr0Og+cNkSOVTLyoxbeLApf4C1Q0ltNitWsZ4FWdQJJ4lf+qbCYnkSMcghOPW7oEFmjExW2khVfwg5v51JPlxbvMmnyoWXuAAvORHawMuqWvqq01KANnvAHp38II9Fb0mcyrYIfh+QvHUQpCYR32GX1LKIw3RzJSkBu4COr3/LVytehr0t2LYhVLiU7tCYKye+AUzjP2ODXhL7mqgUjzIlmS7cmE/Hc4e5fmBe0LqJ/5JyeJzIKOhmgUoacGRYhZQzWs7yMutBtyBNZNxmTx6z7AjWZ0Q5+aPRpEPp7VqFnW/A24dkgfMdBi5vTEAa+h6P6v/PccgmCioSC+KS068ckEkpHN3y9nsz0flqQCQklF/mGj1gXWygAs5BqrkaVRVCqZylVprFZ2pA+JDzMQl/uPAJ/VdkXO7KO576XdWWx7b/5UFYBR2pCDwF3Jcq7wQmzpXiIqNjNJYMi1rqPflGOx3f9mBhHpW2pdfpSonolDad+VgLkPpnbKmP6MFDnAUwEXbdkMNGaIisjwH5+4pQuedsorsQbTBIgJOj1D1DSKMgfO8rBQ04gr9iPZxpLDlaAZCwdDSeZqD4ZT+k3uEXHOEBU7vVCCcPT8Iaj8AJxJXj2nTZZCro2/aOv/XWgkfWHHBQ==,iv:jjddeJEWRCm3s/BvpEXAndEvIa8ADDT8iOS37IbOaGk=,tag:tfhCAOsN1NiIqMUkSK3wyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZzU0Q3VIZERoL1NPVDgw
            MTJ5UjBHTUU2eVVPR2xaWmpxVXAvcFo2WFRjClRDZCt0QmExRkdaM09NbFhvZXJC
            eC8xdHlZRHVkT3ZjVGNnaFRJUlF6S0EKLS0tIDg4SEU5YmhXWWFuSy9oVmIrVkIr
            OWdUZkwrT3FESFhUQWhqQW5GMTgxR00Kb8/uVcLKChbGO/Q95fadehhBpbis/Dzx
            1B/mxZahcqhUE6+oHFv0dGi1y71V3pMh/2BvqBkO64wUlBar51Zbfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-27T04:08:43Z"
    mac: ENC[AES256_GCM,data:JyEar3Mtf4DuZxx2VXHYJC+LaRn09CBvOzo5SK8v2cNTCH+EZdSH0W7QArJxqK09h+LKrRCGxDqC7UkcI2e0ZDYGyWsQ18yxvEhA+T4scr/6iIwIp2a7thi8j4210YOobPVR/q8H3y+S4KtWco2zWiGkseoPB0yVnGT53a89v0I=,iv:fxWiGsbrrbScIWdqKfvxKND1v7SF4fJfTYWSN8F0gM4=,tag:/5zQq36Isat5LnfV9mqECA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
