apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:2qRQy9619R28GGt09MemjxIDB2jf0pXjcl7f3BoNdogPF04wPY9AIPtTkNwS3n0x2hczuRfr5V464cNm4uuw0Q==,iv:g36OFrJnTAXeJVYXqLaERQgbE97AhD6h0ATS8WNSTvU=,tag:OBiiamL6n4yvur7g0bE+8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZzU0Q3VIZERoL1NPVDgw
            MTJ5UjBHTUU2eVVPR2xaWmpxVXAvcFo2WFRjClRDZCt0QmExRkdaM09NbFhvZXJC
            eC8xdHlZRHVkT3ZjVGNnaFRJUlF6S0EKLS0tIDg4SEU5YmhXWWFuSy9oVmIrVkIr
            OWdUZkwrT3FESFhUQWhqQW5GMTgxR00Kb8/uVcLKChbGO/Q95fadehhBpbis/Dzx
            1B/mxZahcqhUE6+oHFv0dGi1y71V3pMh/2BvqBkO64wUlBar51Zbfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T05:26:17Z"
    mac: ENC[AES256_GCM,data:XP1RvR73MwamCJ7CpQ+mlq4hHhIJ0KHIgjUh5QDoc9yE9jTw28NFmkBpxH0xMMACwzX5IsyMyzjUpuooFxpkeyTm9QKDvPH6tvaxKD5ttxyCaQkkeBKnTb0V7D8I3fmlDrzPJtLa+9Z4F1GgRvG/vZFr/DmtYlC1mVaBnJ4sjBM=,iv:NZ9cM0rStQsyaoUCIAtmiQhzWk2kYYl92qUeZ/ZaYMc=,tag:ubg52ln97DfY1wWHWW78uw==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: kopia-repository-secret
stringData:
    repository.config: ENC[AES256_GCM,data:wt3ikM8SwuRA76hgTDJcJnugdvvALZz7ZRT/359YDdBwHHmQD4posT806fz+iIsxseaWcNzd6M1kdCEH11JcZOCOcgs7oPufo8OBTNT8zBBAL2RXANa7gUJoLjlZn4YQJ/tHG/liVJV4tkVRKHgE2q1D/Mn7UH7ejj3HAM8W+LT+R1ydOXfUD1ioecvDCl5eGHQOKR4mfdbvhV70bvr21DGraC02oQX3coc04KhUopfJQhOkvJNS2JmKrZ3d3ws8Xmcj9En6Cjf9DXC057hI6U2LLpmtQwLuxLFHCwRUqJWP8N/AK8qK7DMKoTJAHiMWqy2X46DwW3nQH5MmbmCu+u+ck5o6MFK0gTjI5YDt/6mhnW6BUSemI7nBSKafpT41l6kxjT32WpJ7UZm0ADUTjp25GqN/YeOHHLT0A+zDpKNKUJULz6ceqx4mOBlwNn/l/xb/qG5KENeFlSgujUKLuzLMoO7tTjAbTujx6PO9YL8Q3Uye56RG4EE0LQcqpCFTCFj5kGHtTYG3+1ZdfDynMQ==,iv:0SfamAJIIAD4gEnT5i+a5q1QSppmzGfZr5O0DIxRTuQ=,tag:utb/r57ySmxrJKsMmcnKyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZzU0Q3VIZERoL1NPVDgw
            MTJ5UjBHTUU2eVVPR2xaWmpxVXAvcFo2WFRjClRDZCt0QmExRkdaM09NbFhvZXJC
            eC8xdHlZRHVkT3ZjVGNnaFRJUlF6S0EKLS0tIDg4SEU5YmhXWWFuSy9oVmIrVkIr
            OWdUZkwrT3FESFhUQWhqQW5GMTgxR00Kb8/uVcLKChbGO/Q95fadehhBpbis/Dzx
            1B/mxZahcqhUE6+oHFv0dGi1y71V3pMh/2BvqBkO64wUlBar51Zbfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T05:26:17Z"
    mac: ENC[AES256_GCM,data:XP1RvR73MwamCJ7CpQ+mlq4hHhIJ0KHIgjUh5QDoc9yE9jTw28NFmkBpxH0xMMACwzX5IsyMyzjUpuooFxpkeyTm9QKDvPH6tvaxKD5ttxyCaQkkeBKnTb0V7D8I3fmlDrzPJtLa+9Z4F1GgRvG/vZFr/DmtYlC1mVaBnJ4sjBM=,iv:NZ9cM0rStQsyaoUCIAtmiQhzWk2kYYl92qUeZ/ZaYMc=,tag:ubg52ln97DfY1wWHWW78uw==,type:str]
    version: 3.13.0
