---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelfmark-gluetun
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: shelfmark-gluetun-secret
    template:
      engineVersion: v2
      data:
        WIREGUARD_PUBLIC_KEY: "{{ .SHELFMARK_GLUETUN_WIREGUARD_PUBLIC_KEY }}"
        WIREGUARD_PRIVATE_KEY: "{{ .SHELFMARK_GLUETUN_WIREGUARD_PRIVATE_KEY }}"
        WIREGUARD_ENDPOINT_IP: "{{ .SHELFMARK_GLUETUN_WIREGUARD_ENDPOINT_IP }}"
        WIREGUARD_ENDPOINT_PORT: "{{ .SHELFMARK_GLUETUN_WIREGUARD_ENDPOINT_PORT }}"
        WIREGUARD_ADDRESSES: "{{ .SHELFMARK_GLUETUN_WIREGUARD_ADDRESSES }}"
  dataFrom:
    - extract:
        key: protonvpn
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelfmark
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: shelfmark-secret
    template:
      engineVersion: v2
      data:
        OIDC_CLIENT_SECRET: "{{ .SHELFMARK_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: shelfmark
