---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: esphome-secret
    template:
      engineVersion: v2
      data:
        ESPHOME_USERNAME: "{{ .ESPHOME_USERNAME }}"
        ESPHOME_PASSWORD: "{{ .ESPHOME_PASSWORD }}"
  dataFrom:
    - extract:
        key: esphome
