---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app esphome
spec:
  chartRef:
    kind: OCIRepository
    name: esphome
  interval: 1h
  values:
    controllers:
      esphome:
        containers:
          app:
            image:
              repository: esphome/esphome
              tag: 2026.7.2@sha256:fc149ed99a3d907135f9dc5a5ee5ae76109b009979d04d0e05718151f492451a
            env:
              ESPHOME_DASHBOARD_USE_PING: true
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 100m
                memory: 500Mi
              limits:
                memory: 4Gi
    service:
      app:
        ports:
          http:
            port: 6052
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: esphome
