---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: emqx-operator
spec:
  interval: 15m
  ref:
    tag: 2.2.29
  url: oci://ghcr.io/emqx/emqx-operator
