---
- hosts: all

  roles:
    ###
    ### Requirements
    ###
    - role: nas-users
      tags:
        - nas-users
        - nas

    - role: geerlingguy.nfs
      tags:
        - nfs
        - skip_ansible_lint

    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint

    - role: vladgh.samba.server
      tags:
        - samba
        - skip_ansible_lint

    ###
    ### NAS Roles
    ###
    - role: nas-general
      tags:
        - nas-general
        - nas

    - role: nas-docker
      tags:
        - nas-docker
        - nas

    ###
    ### Applications
    ###
    - role: bazarr
      tags:
        - bazarr
      when: (bazarr_enabled | default(False))

    - role: emqx
      tags:
        - emqx
      when: (emqx_enabled | default(False))

    - role: homeassistant
      tags:
        - homeassistant
      when: (homeassistant_enabled | default(False))

    - role: hyperion
      tags:
        - hyperion
      when: (hyperion_enabled | default(False))

    - role: plex
      tags:
        - plex
      when: (plex_enabled | default(False))

    - role: portainer
      tags:
        - portainer
      when: (portainer_enabled | default(False))

    - role: prowlarr
      tags:
        - prowlarr
      when: (prowlarr_enabled | default(False))

    - role: radarr
      tags:
        - radarr
      when: (radarr_enabled | default(False))

    - role: sonarr
      tags:
        - sonarr
      when: (sonarr_enabled | default(False))

    - role: traefik
      tags:
        - traefik
      when: (traefik_enabled | default(False))

    - role: transmission-with-openvpn
      tags:
        - transmission-with-openvpn
      when: (transmission_with_openvpn_enabled | default(False))

    - role: unifi-controller
      tags:
        - unifi-controller
      when: (unifi_controller_enabled | default(False))

    - role: zigbee2mqtt
      tags:
        - zigbee2mqtt
      when: (zigbee2mqtt_enabled | default(False))

    - role: zwave-js-ui
      tags:
        - zwave-js-ui
      when: (zwave_js_ui_enabled | default(False))
