---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookboss
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: bookboss-secret
    template:
      engineVersion: v2
      data:
        BOOKBOSS__DATABASE__DATABASE_URL: >-
          postgres://{{ .BOOKBOSS_POSTGRES_USER }}:{{ .BOOKBOSS_POSTGRES_PASSWORD }}@postgres16-rw.database.svc.cluster.local:5432/bookboss
        BOOKBOSS__ENCRYPTION_SECRET: "{{ .BOOKBOSS_ENCRYPTION_SECRET }}"
        BOOKBOSS__OIDC__CLIENT_SECRET: "{{ .BOOKBOSS_OAUTH_CLIENT_SECRET }}"
        INIT_POSTGRES_DBNAME: bookboss
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .BOOKBOSS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .BOOKBOSS_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: bookboss
    - extract:
        key: cloudnative-pg
