apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard
stringData:
  rook-ceph-dashboard-password: ENC[AES256_GCM,data:yAcPHC7mmJPnD/iXWO5ddE+JXtxoVT4HmE+fSRID54YGKLk1XBEDk1XyNAEsasuD5UlkGTPoZWWLNzYuhzBDpQ==,iv:CLGLaDPIjYt/Itsg57xuJnDycoS6zioYjPWeSFrgDq4=,tag:8L+zLqmhXeZl07Kq1bkGBg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZmt2MHZEUDkrTFU4OWM5
        d2NsSjBqQjF5Y0dIWGFoakttdWRWaXdOb2dnCjI3WE5LYm01OUhPMVJ4YndUdXhk
        Q1VGYS9JbDlSbnFROG5PUmFVS3ZvQWsKLS0tIHE1bWM2cGNjQkVUbEJSL2syd2xs
        cy9ZWmlFQWJNTU9TUGFYak9ub2V3dU0KNq4iLidDfq13ubyGmXxTMCuf3uNMO6N9
        SK/Tm11JhrPveYijz+2mInAk4b+MoJzmSyceO6WpVhGRSADYyF81sg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-04-21T04:10:48Z"
  mac: ENC[AES256_GCM,data:apLhsB1kPHt5zPuS3WJRTuIKNTsn1qgNb85UXhSEb2qh9yLuULLxqKYqJFwZ25fpKVp9xbnSiBWH7OKmwZf9ljYWwTvUQMzccBt2i6L+zlZowXV3vVRqprKMVJTqsSrl+l0g0KkSFy/MkDRwZKXpA4z45tD4YKqlmQXY+yUqCNY=,iv:69MuyWpyD5oSwh1oNrgyruSWp/UL8pEn0yvsCzS8vys=,tag:A/a4NQrFJlYqsHvtGKopjA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
