apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:aOLb08oJmxculpcOg4eE2C19Nj32zI748f2+rhI8/xJvZvCdlUB1gGzPx9Q=,iv:q7v5UgGtgv1arJdp7hvzW87aVY0VoBOd0PbpIZZcNR8=,tag:ZgZeTg0xKxGL+Z8xXjE26Q==,type:str]
sops:
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZzU0Q3VIZERoL1NPVDgw
            MTJ5UjBHTUU2eVVPR2xaWmpxVXAvcFo2WFRjClRDZCt0QmExRkdaM09NbFhvZXJC
            eC8xdHlZRHVkT3ZjVGNnaFRJUlF6S0EKLS0tIDg4SEU5YmhXWWFuSy9oVmIrVkIr
            OWdUZkwrT3FESFhUQWhqQW5GMTgxR00Kb8/uVcLKChbGO/Q95fadehhBpbis/Dzx
            1B/mxZahcqhUE6+oHFv0dGi1y71V3pMh/2BvqBkO64wUlBar51Zbfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T06:15:31Z"
    mac: ENC[AES256_GCM,data:VBr/dApR3DQIZ6ijAjiar9Ow9VPqW4CJSOH5ZoWQQtStDZnbufi5U3H0wKSF/duZzHtf750ulknKQ0FTCATwcBgfYQfjzuhcmgucdmAEfkWmPaJsW6wf8U9eF6zRmEzfLgKb2vGmuIIHuz4yePnkcEiEF1eNI2elWvz5eAU7kxg=,iv:UZajX53ti2bNk3W4j6FZPk/oDRch3MYnICglQ0I9mao=,tag:PXXsJR2yJdLL/IMAeGffxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
