apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:FdPnPA82wk21z8ScYDtnj/YCWuHFZLOCF0yIwom7CxW/2n/f+T4+SzYxR29UCcyPQXmKYzRehW8bm8St3JC8t0sKdyTUbycO0VKMis+fQcz+EbQYhxssct8QWjmWrHrhA6ZkTzti+nPmmlWu+bIpArfjdyKQ/0Xfj15Erbi68bLoo58nAMDBOpvJzbg+2egwzTJ1dJPjNlFsYN33jTKEKZt8KvMENLZ+gg1LChl9yqBj1doD,iv:gT5mrE1lfrte+H+hbJjH6vwfmJuleHY+uo1rBWJW7YI=,tag:o4lXAnJXTT4vE00ByXFMtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZzU0Q3VIZERoL1NPVDgw
            MTJ5UjBHTUU2eVVPR2xaWmpxVXAvcFo2WFRjClRDZCt0QmExRkdaM09NbFhvZXJC
            eC8xdHlZRHVkT3ZjVGNnaFRJUlF6S0EKLS0tIDg4SEU5YmhXWWFuSy9oVmIrVkIr
            OWdUZkwrT3FESFhUQWhqQW5GMTgxR00Kb8/uVcLKChbGO/Q95fadehhBpbis/Dzx
            1B/mxZahcqhUE6+oHFv0dGi1y71V3pMh/2BvqBkO64wUlBar51Zbfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T23:34:59Z"
    mac: ENC[AES256_GCM,data:1KhV7GTRHwvzvmkT12ZSw16+jk0os3bl7Rz4HFLw9O+GK6wSFut3YPRLWAdbZUCXPmRP6d8F8C1ZlTDoqHeu5UefVUGHCwt3YPQ1oojAHxd3QqW1IF/zjNplJa2AN1Lwgy7ndYNlY3vPpHu8TmVZuED8HQIO66rrQtHvcGQJUt8=,iv:MXeYG/W81okxcurunjyjnE/A4XMIEFmtLRetU5sih9w=,tag:xR4/zDG+iCYD2dIiDMZv+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
