apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:QB44Ub36/TVlStHqcs9vY0kQOrrJmN9kEmUXTLdIaOTUnQ9Sc3sCcgPkUC+vfzSJNkf8DJxCF5s7sDxr7f/oL2CIq/7Oz/qwbBS56PX9eZLKLrCyZHONRRTuA8G2p0yAzmaXrUMeW+GLub5mUMbmNK+tIFN06YTnqSmM8mhQm5KAGOeOZk4gFnnV5UJ5bF1i4NpYKCPiknO0DO9DIchcyxBxpCVx07YLXGUn8DkrgdqkXOaS,iv:0JBof+/LmJIoYEivPlmlqPCnMX8cm9gfNn7vEf93H1g=,tag:4LSg5f53uZ8AhFn5KVT5/w==,type:str]
sops:
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZzU0Q3VIZERoL1NPVDgw
            MTJ5UjBHTUU2eVVPR2xaWmpxVXAvcFo2WFRjClRDZCt0QmExRkdaM09NbFhvZXJC
            eC8xdHlZRHVkT3ZjVGNnaFRJUlF6S0EKLS0tIDg4SEU5YmhXWWFuSy9oVmIrVkIr
            OWdUZkwrT3FESFhUQWhqQW5GMTgxR00Kb8/uVcLKChbGO/Q95fadehhBpbis/Dzx
            1B/mxZahcqhUE6+oHFv0dGi1y71V3pMh/2BvqBkO64wUlBar51Zbfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T06:17:44Z"
    mac: ENC[AES256_GCM,data:FKXqawyJTFsaYK26UI+R2uvdMxuH4uwZBZwYR144AJWt0rWkfd+iqTN5jWxJf/B4jbVJFKKqL14bGT988LicIy+aGQjQD8aVb8eBYzhZaT5YW8r2OMiOjRAriexo8BmHeps4wUY3S1M9+4MheHGBDY1i8fkRkY8GA8v2j9vYBpI=,iv:BijOs6J/cwR8QE1RtLn5V+xIjHxlL5nwF0rN/UVStFg=,tag:rX3nk6iUuFyF3s6mcyEgQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
