---
hyperion_enabled: false
hyperion_available_externally: false

# directories
hyperion_data_directory: "{{ docker_home }}/hyperion"

# network
hyperion_ui_port: "8090"
hyperion_api_port: "19444"
hyperion_server_port: "19445"
hyperion_hostname: "hyperion"

# specs
hyperion_memory: 1g
