---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./qbtools-config.sops.yaml
  # TODO: Fix dns with gluetun and reenable this
  # - ./helmrelease.yaml
