---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
data:
  config.yaml: |
    storage:
      type: memory
    metrics: true
    endpoints:
      - name: grafana
        group: internal
        url: http://grafana-service.observability.svc.cluster.local
        interval: 1m
        conditions:
          - "[STATUS] == 200"
      - name: victoriametrics
        group: internal
        url: http://vmsingle-victoria-metrics.observability.svc.cluster.local:8428/health
        interval: 1m
        conditions:
          - "[STATUS] == 200"
      - name: vmalertmanager
        group: internal
        url: http://vmalertmanager-victoria-metrics.observability.svc.cluster.local:9093/-/healthy
        interval: 1m
        conditions:
          - "[STATUS] == 200"
      - name: victorialogs
        group: internal
        url: http://victoria-logs.observability.svc.cluster.local:9428/health
        interval: 1m
        conditions:
          - "[STATUS] == 200"
