apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:iuP2yPjZrKLgstnX1mk2Wrc0/LfXqlEXSzv/5tS8AoQMgDHuoHVmcXLEsmJFVHxeilYm1nE=,iv:rlCXy1ebOuGwGppobJyekj5W64uAQyBZHoJFASQZrD4=,tag:s7alaaErHvQabjUVaGHRQA==,type:str]
sops:
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeUFpeTlaV0R6NTYydjg1
            WXBTWU13b2Q3NEdVeUV5dUNwUXdiZXFhRVMwClNSNXovRFprRDgxcTFNQmFpeUlJ
            R3p4dG9vQTVObFJuSEpuTk8veU1EN1kKLS0tIHp1a2xJZ1VJZEJzZTNkdkpYVGxX
            aFNKWEZIN2pPRXFad1R3NTdZWUtKREEKrVK7M6wZzNxzI8WU8u8F/GN5a9JG81qs
            +BFL5TbzwN3XkcceZx6Qee982lHJTYlaFb+qLhJ5ORel/zyfCM6InA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T05:49:15Z"
    mac: ENC[AES256_GCM,data:AAkPOfuyQIuG+LCy9Z/X7CNQK5L9L3B5ZnbnJriRl3qWgNm/FbTULW86gblc/1vrkeHMlL+NoxD9qlIm9xINANg6baE8HiU53+mqi9u99W2PPHSpXZmUc9yOxFOEDQ8OGBp4i8zDqqgJcmzUv3T3KvOWat4pj/MxTNWt+zEHkCk=,iv:RbaikwUjt0s0r7CzrQzku1zgHTKe5k9xQGTjS5pglHg=,tag:WE6a2RtbJcVPsu8OW7Hc8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
