---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.20.90:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.20.90"
additionalMachineCertSans: *sans

clusterPodNets: [ "10.69.0.0/16" ]
clusterSvcNets: [ "10.96.0.0/16" ]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "nuc1"
    ipAddress: "192.168.20.21"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/4b3cd373a192c8469e859b7a0cfbed3ecc3577c4a2d346a37b0aeff9cd17cdb0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "88:ae:dd:0d:b7:97"
        dhcp: false
        addresses:
          - "192.168.20.21/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.90"
    patches:
      # Encrypt system disk with TPM
      - |-
        machine:
          systemDiskEncryption:
            state:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
            ephemeral:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
      # Tag node as having Intel integrated GPU
      - |-
        machine:
          nodeLabels:
            intel.feature.node.kubernetes.io/gpu: "true"
  - hostname: "nuc2"
    ipAddress: "192.168.20.22"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/4b3cd373a192c8469e859b7a0cfbed3ecc3577c4a2d346a37b0aeff9cd17cdb0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "88:ae:dd:0c:fb:79"
        dhcp: false
        addresses:
          - "192.168.20.22/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.90"
    patches:
      # Encrypt system disk with TPM
      - |-
        machine:
          systemDiskEncryption:
            state:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
            ephemeral:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
      # Tag node as having Intel integrated GPU
      - |-
        machine:
          nodeLabels:
            intel.feature.node.kubernetes.io/gpu: "true"
  - hostname: "nuc3"
    ipAddress: "192.168.20.23"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/4b3cd373a192c8469e859b7a0cfbed3ecc3577c4a2d346a37b0aeff9cd17cdb0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "88:ae:dd:0d:b6:ce"
        dhcp: false
        addresses:
          - "192.168.20.23/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.90"
    patches:
      # Encrypt system disk with TPM
      - |-
        machine:
          systemDiskEncryption:
            state:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
            ephemeral:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
      # Tag node as having Intel integrated GPU
      - |-
        machine:
          nodeLabels:
            intel.feature.node.kubernetes.io/gpu: "true"

# Global patches
patches:
  - "@./patches/global/machine-api-access.yaml"
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-openebs-local.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"
