apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hQYalxgr48+row==,iv:V/RklmvtxRIF5I64swi99k7SzMQ+Sbo9dysgo3qB6VU=,tag:BF92qyrq0ba6RaXXAvZCMQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:NADfmomLIPaViXmyR65mKuFCC6jMFeEzUOWIoHmuokpaKQ==,iv:xiYWd+yfjDxrhkGfxGsUPvbbsNSrHJcS5rBp9qAbk9U=,tag:rBmYOmLPbASK2twiSULuzQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:fKLREQ/4HzkholAJrhY6FNfMJvM0uo1dQdRSVH2MNpr/zlAm,iv:GBXtuPWxjk0P4fDdwrSkRG3+bPNycv65WBGJJpsL2rU=,tag:UoXa2CB+poDzEJA2d3DsuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZDFGVEJWUlNZdmV4enl0
            N1grSmloVkhaaXA3MVMrbHZqSzZIMmVwOW40ClJoTTAwcm13MXdSdVNjNCtFSlg0
            eHhlZkE0S3dUYzl3UVgzbHcwalltMFEKLS0tICt3dzZQOWh6STBSS0IxRlp1NFRQ
            Rm00NklRNFR4TExheVJzdjRmazVLTjgKY2lJFluLkVi59wjsFITSNQ7Zpct4A6fE
            5arxMXdPoozIbsfnrLv28kVTAMezWhrWdZjdZhkCTMLmvFNgjfnW4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-23T05:18:15Z"
    mac: ENC[AES256_GCM,data:E2YhOkhJW8oKpZCy2HZ/dpTxwGHChZpvC6qiFJcTp9oWQo9xE8uwREfTPtoZywvT+jcixgI2i05CM4efWrxbaENE/FgWKqdg4F03jE0vYh3JaIzABzJn7OkdFbWOwMarUuZEG/ioQDGCPIeKdnGIH3tuPnQLLrdo4UtNj8+xq6c=,iv:9sOVzZ98ciqgY30KnxkmXZMIg+1V8bE9NUwpPt4mZKc=,tag:YB9Y64GUVMwsZCf1QK+rbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
