---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: slskd-secret
    template:
      engineVersion: v2
      data:
        SLSKD_API_KEY: "{{ .SLSKD_API_KEY }}"
        SLSKD_JWT_KEY: "{{ .SLSKD_JWT_KEY }}"
        SLSKD_PASSWORD: "{{ .SLSKD_PASSWORD }}"
        SLSKD_SLSK_PASSWORD: "{{ .SLSKD_SLSK_PASSWORD }}"
        SLSKD_SLSK_USERNAME: "{{ .SLSKD_SLSK_USERNAME }}"
        SLSKD_USERNAME: "{{ .SLSKD_USERNAME }}"
  dataFrom:
    - extract:
        key: slskd
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd-gluetun
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: slskd-gluetun-secret
    template:
      engineVersion: v2
      data:
        WIREGUARD_PRIVATE_KEY: "{{ .SLSKD_GLUETUN_WIREGUARD_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: protonvpn
