---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./externalsecret.yaml TODO: Something wrong with the way this is being parsed. Switching back to sops for now
  - ./helmrelease.yaml
  - ./secret.sops.yaml
