apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:yHaRzm7YIik=,iv:rFUK+26qlbLW2PpHM5m4pszIIRIb3ty7guEoD9JINf4=,tag:UIkODd6Yi6L5iLzYkuvfpA==,type:str]
    password: ENC[AES256_GCM,data:QMCNRrvAyP91Tl7MMxYCe6CI1pNZJh74SOu3KshUUy+2aRVb8nvkK8fMz70DnI1JlooCp7QWAK6fjGFw6T5XLw==,iv:txc3wWtTXmJGKfjpgfJQP1e2dbwytyb8PLeKKkP8lWQ=,tag:3sK3Yu0Be6nBUYY/kOb90w==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:FVS21HPu598zTVbVt4JV2t7+LtCuzoFYeee9iqEe1jg=,iv:bPRkUJwjcFtEFLLqiR13xpSvDEpMlUYyKOGbCu+zs9M=,tag:SQHGJuT9LWWEBwYFrHuUbQ==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:MvEqtRBDXg+DQsQrZqb6v9z4lVN+ql07W8R/p5+98ZAwHKV8at8Gqydj15WgZQ9+y7p4Rj2szczgsAfSg8UzbA==,iv:Q+b9TQC4Rh3xyQqPTZQFFdG6R6cZxT4uomLEbA1p9zk=,tag:L5wr/ICCaWrB6pVQuvnGQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUXFaUXRSL2ZuSnE2QmZW
            ek9SRStzQ0x2SlAzWTZ3WTYySlNDeHk2ZW5JClZxWU5URmd1VG85YzJ4b2FiOFdD
            emMxMVh1SmVLVVFobDQvaXVUSnpkRWsKLS0tIEVTc1R0N28rM2J0RGw3Q3dEWVJp
            MmxhbVlmRHp1emwxWVJ6bDJ6UjNhV2sKMdrdbKBoeojoAcmQQ/gwGJfxf8fsuvdQ
            OZdUTtOH/3y0WXSxTvXOkdDrLNETHKpaO5SMncfQPqGIDA/3NeTo6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T03:37:26Z"
    mac: ENC[AES256_GCM,data:rHCuGHpTiJMidGvfqg5Sit4WV18g1QrOl9uZiLK35IBib7mbR/BxEBGRiYIFnUVU1fgMYlkPJJZZHwOaHCLB7z89aV947xNEPtl327GV2i0QAq7TAy+d4FzZRpY9j3wZsXRUwYnrT2KqYTDACyKNXNwULTPTthzvWAGvkWIB5hU=,iv:TxoCCVVA8P0S2qR1Rc4MHrYbUuDb1ksp83ZI+TYT1q8=,tag:27gm51Px8ypLaHBRYjHnWA==,type:str]
    version: 3.13.1
