apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:yHaRzm7YIik=,iv:rFUK+26qlbLW2PpHM5m4pszIIRIb3ty7guEoD9JINf4=,tag:UIkODd6Yi6L5iLzYkuvfpA==,type:str]
  password: ENC[AES256_GCM,data:QMCNRrvAyP91Tl7MMxYCe6CI1pNZJh74SOu3KshUUy+2aRVb8nvkK8fMz70DnI1JlooCp7QWAK6fjGFw6T5XLw==,iv:txc3wWtTXmJGKfjpgfJQP1e2dbwytyb8PLeKKkP8lWQ=,tag:3sK3Yu0Be6nBUYY/kOb90w==,type:str]
  aws-access-key-id: ENC[AES256_GCM,data:6Y2taQ==,iv:qtY0Q8qc8ZGoJ5IMHd99pbvLwVVv51olBY8inoemJwA=,tag:UbZuEWvO2E2oDyUrU6s6ng==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:fLkaqna5odNrAGnjaRnx7EODon4Zh8OM3VfmploCY9vTqSLCWAc/tJqaRWo=,iv:RcGGWzauloW3P/09B18jSjMAbXMCU4a4NXgKrpLPfVk=,tag:w2o4uhdP1UPm/ltJ1lVQIg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUXFaUXRSL2ZuSnE2QmZW
        ek9SRStzQ0x2SlAzWTZ3WTYySlNDeHk2ZW5JClZxWU5URmd1VG85YzJ4b2FiOFdD
        emMxMVh1SmVLVVFobDQvaXVUSnpkRWsKLS0tIEVTc1R0N28rM2J0RGw3Q3dEWVJp
        MmxhbVlmRHp1emwxWVJ6bDJ6UjNhV2sKMdrdbKBoeojoAcmQQ/gwGJfxf8fsuvdQ
        OZdUTtOH/3y0WXSxTvXOkdDrLNETHKpaO5SMncfQPqGIDA/3NeTo6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-08-28T04:41:00Z"
  mac: ENC[AES256_GCM,data:wy0w1l9g94x0TT5NTUs9RI06Nbzvj2ytB7v17ck1KW+RHjyR3fn+DB1letCnOPJB19uLB7NwxShoVpjSrqhAUYmCiNOn882dHzdpeDVQdoH89i6j2aVk3kwIx/54a2Lg8oWxftezngEn+9++u/NGsmjF4xKw+T+ViEVCURC0CIk=,iv:zXy9tZg+Ww3QBAGp1IaSmXoexwH1Ri+Lyg2rECBlb30=,tag:Bm9VD6cdYIwj1f2hyNbLsA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
