---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dragonfly-operator
spec:
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: dragonfly-operator-controller-manager
    crds:
      install: true
      keep: true
      annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
    manager:
      image:
        repository: ghcr.io/dragonflydb/operator
      resources:
        requests:
          cpu: 10m
        limits:
          memory: 128Mi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              control-plane: controller-manager
    rbacProxy:
      enabled: false
    serviceMonitor:
      enabled: true
      interval: 1m
      timeout: 10s
