---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: music-assistant
spec:
  chartRef:
    kind: OCIRepository
    name: music-assistant
  interval: 1h
  values:
    controllers:
      music-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/music-assistant/server
              tag: 2.10.4@sha256:37a9a2776e838a754c9f5b38c432567389952304e7cb8f6b44b6cd28043de6de
            env:
              TZ: America/Los_Angeles
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8095
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "media",
              "namespace": "kube-system",
              "ips": ["192.168.7.22/24"],
              "mac": "a2:38:a0:5e:11:fa"
            }
          ]
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: music-assistant
        ports:
          http:
            port: *port
          stream:
            port: 8097
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
    persistence:
      data:
        existingClaim: music-assistant
        globalMounts:
          - path: /data
      music:
        type: nfs
        server: 192.168.20.11
        path: /data/media/music
        globalMounts:
          - path: /music
            readOnly: true
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
