---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rook-ceph-dashboard
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: rook-ceph-dashboard-password # rook-ceph expects this name
  data:
    - secretKey: password
      remoteRef:
        key: c2168596-3fd0-4c64-b9d2-b234006fb34d
