---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  dependsOn:
    - name: snapshot-controller
      namespace: volsync-system
  interval: 1h
  values:
    enableDiscoveryDaemon: true
    image:
      repository: ghcr.io/rook/ceph
    monitoring:
      enabled: true
    resources:
      requests:
        memory: 128Mi # unchangable
        cpu: 100m # unchangable
      limits: {}
