apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:xFCF2+tqYVqqC8yDAjUcKoh9IFHghmVI8I86k+Av1tXcqZvlhm9GCQ==,iv:Y5+mxjKar7zB9jztJ2uhJ3DLP+4VCr35CSxKKDGbxTE=,tag:mnqsBSwD9lqTPsn2vLSnhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nzr5yww67m24y5ecsrz5wte3whjtjqfj0dgfzjtq996k3kvdav3qrlruy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMFpQdnFHNnNyZWo0SlVG
            b2hUdldVaW44cERwcHRkdWQycnVxU3pDdXlBCkRHTElkTWRsOE4yNEladS9VNEhS
            QmpNa0VobENSUE5wWDVRS0NuY3F5RzQKLS0tIHluSW4rQ3h3WWJjY0xzd2M4ZElN
            Vit2TE9WdHBxMXRoTFM5eVk2NGd6S0UKlnJhB+rYO8n9x7jJV5t24wWA58YleyFE
            BnOVuGjku3SZ3sCTFaFFJoWBKPnNFsPXnKR3mCO/LdRxXBrI14+yiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-18T21:21:43Z"
    mac: ENC[AES256_GCM,data:q780IZQCWbCQN1uwPhzNYTWJ04ICP0dhcbDDqgnBZeZobUkEE2QLRib8XjLffqtDk2mnK+0ci4q+nUJYbcKWtIsJhtaxcccIgVuU0IEBVDo6/+BHjl+q5KzaLrvGp6JtKkzgnWpAMS+iiIUseK7ERhlCf6dW0eXTlc4M1BY2CjQ=,iv:oZlUwxS2uPEqdLvhoockzY1KLoB0jpV1YPwgtNjnkJI=,tag:rezbKhlKp5xLSalK7eUu3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
