---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: intel-device-plugin-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/intel/helm-charts/intel-device-plugins-operator
  ref:
    tag: 0.36.0@sha256:24ec70426a851c04e97efb61a4664479fbe1986ac74e39f497c03cce9b7bc282
