---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: intel-device-plugin-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/intel/helm-charts/intel-device-plugins-operator
  ref:
    tag: 0.37.1
    digest: sha256:97008939007a281496381b58088229744a74618fdf6cd416742daa197cd98edd
