---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: external-secrets
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.5.0
    digest: sha256:6b8ef5067976d0aa6195f6f173a4841ef66a53b167f3a28b4b3b9593d2063cf1
  url: oci://ghcr.io/external-secrets/charts/external-secrets
